# db:
#   host: "db.eucgveokehsssslfihwv.supabase.co"
#   user: "postgres"
#   password: "#asdf$a4%^asd"
#   database: "postgres"
#   port: 5432
#   sslmode: "require"

db:
  host: aws-0-ap-southeast-2.pooler.supabase.com
  port: 5432
  user: postgres.eucgveokehsssslfihwv
  password: "#asdf$a4%^asd"
  database: postgres
  sslmode: "require"

server:
  port: 8080

logger:
  timeKey: "timestamp"
  fileAppender: false
  consoleAppender: true
  fileName: "log.json"
  logLevel: "debug"
  traceKey: "debugId"

jwt:
  secret: "kitchen-api-super-secret-jwt-key-2026"
  expirationHours: 24

cors:
  origin: "https://restaurant-ui-omega.vercel.app"

app:
  url: "https://restaurant-ui-omega.vercel.app"
