# db:
#   host: kitchen-db
#   user: "postgres"
#   password: admin123
#   database: "postgres"
#   port: 5432
#   sslmode: "require"

db:
  host: aws-0-ap-southeast-2.pooler.supabase.com
  port: 5432
  user: postgres.eucgveokehsssslfihwv
  password: "#asdf$a4%^asd"
  database: postgres
  sslmode: "require"

server:
  port: 8080

logger:
  timeKey: "timestamp"
  fileAppender: false
  consoleAppender: true
  fileName: "log.json"
  logLevel: "debug"
  traceKey: "debugId"

jwt:
  secret: "kitchen-api-super-secret-jwt-key-2026"
  expirationHours: 24

cors:
  # origin: "http://localhost:3000"
  origin: "https://restaurant-ui-omega.vercel.app"

app:
  # url: "http://192.168.1.91:3000"
  url: "https://restaurant-ui-omega.vercel.app"

stripe:
  secretKey: "config key"
  webhookSecret: "bla bla"
  currency: "aud"

